@rem *************************************************************************
@rem *      Sample player code for CAT, using Mastersound sample player      *
@rem *                  Written by Tony Stiles, August 1991                  *
@rem *************************************************************************

@rem When program loads, sample player should be initialised.

@first _saminit()

@rem When program ends, sample player should be killed.

@last _samkill()

